version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every weekday
    interval: "daily"
    time: "04:00"
  assignees:
  - pfichtner
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
  assignees:
  - pfichtner
  ignore:
    - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
      versions: [">=4.0.0"]

    - dependency-name: "org.springdoc:springdoc-openapi-starter-webmvc-ui"
      versions: [">=3.0.0"]

